export const FETCH_LATEST_PAIRING_LIST='FETCH_LATEST_PAIRING_LIST';
export const STORE_PAIRING_LIST='STORE_PAIRING_LIST';
export const STORE_PAIRING_LIST_ID='STORE_PAIRING_LIST_ID';
export const FETCH_HUMANS='FETCH_HUMANS';
export const STORE_HUMANS='STORE_HUMANS';
export const FETCH_NEW_PAIRS='FETCH_NEW_PAIRS';
export const RECORD_PAIRING_LIST='RECORD_PAIRING_LIST';
export const ADD_HUMAN='ADD_HUMAN';
